server:
  port: 8084

spring:
  application:
    name: ms-istana-auth
  datasource:
    url: jdbc:postgresql://localhost:5436/authdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Configuracion del JWT (el secreto se comparte con el Gateway en la Fase 9)
jwt:
  secret: dad-upeu-microservicios-jwt-secret-key-2026-super-segura-0123456789
  expiration-ms: 3600000   # 1 hora

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: localhost:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
