server:
  port: 8083

spring:
  application:
    name: ms-gestion-taller
  datasource:
    url: jdbc:postgresql://localhost:5435/tallerdb_test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: localhost:${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        sliding-window-size: 6
        minimum-number-of-calls: 4
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        ignore-exceptions:
          - feign.FeignException$NotFound

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers
