server:
  port: 8083

spring:
  application:
    name: ms-istana-gestion-taller
  datasource:
    url: jdbc:postgresql://localhost:5435/tallerdb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
